### ISSUE TITLE
Any support for .NET CLI?

### ISSUE THREAD

**Issue by Logabe** [gnFur/Monofoxe#11]
Um, hi!
This isn't really an issue but I was wondering if there was any way to create a template via the .NET Command Line?
I'm fairly new to MonoGame so there's probably something that I'm doing wrong.
Cheers, Logan B.

**Comment by Martenfur** [comment]
...aaand why do you need command line, exactly? The point of this is to use graphics and shit. :D 
If you *really* want to hack it in, you can change your application type to console app in the project prefs, this will spawn an additional console window.

**Comment by Martenfur** [comment]
Gonna close the issue since the boy never followed up on it.
