### ISSUE TITLE
Touch input in Input.cs

### ISSUE THREAD

**Issue by stromkos** [gnFur/Monofoxe#18]
I started to implement a touch interface in Input.cs, and ran into issues:

Your implementation of unified buttons makes the touch input code harder than it needs to be for the different use cases.

May I ask permission refactor the code to a more traditional `...State` and `old...State` setup on the back-end. 

The existing API would not change, a hash table of buttons would be faster on lookup, but given the limited size of concurrent inputs, the gains would be non-existent. 

The code will speed up since 6 heap allocations will be avoided altogether, replaced by fixed stack references.

----

In one of your code [comments](https://github.com/Martenfur/Monofoxe/blob/e2e0f6f4756d900d4706a5e12e8c45c6452906d5/Monofoxe/Monofoxe.Engine/Buttons.cs#L5), you stated you did not like the 3 distinct access methods. I agree wholeheartedly.

I disagree with your approach to unifying the inputs: You have simply pushed the problem to the end user in a unified manor.

Dynamic bindings:  

Define common fixed actions as booleans(buttons) Fire, jump, left, right, forward, back, up, down, crouch, back... and axes as floats(or threshold buttons mapped to above actions), mouse delta or gamepad.  Please note the disparity between keyboard, mouse delta and gamepad in this respect. 

Allow a user(or programmer) to specify the mappings as needed.
This allows for the user to provide mappings.

**Comment by Martenfur** [comment]
I mean, sure, go for it. My idea for the touch input is that it should be unified with mouse input in a seamless manner - if you use mouse on PC, same code should work as a single finger input on touch devices. But yeah, new touch-specific methods for multitouch will be needed. I wanted to implement that *someday*, but as I was writing monofoxe my focus switched from mobile games to PC games and I never got around to.

```
Define common fixed actions as booleans(buttons) Fire, jump, left, right, forward, back, up, down, crouch, back... and axes as floats(or threshold buttons mapped to above actions), mouse delta or gamepad. 
```
Hell no. Monofoxe is game-agnostic and will stay that way. Any specific inputs should be defined by your game.

**Comment by stromkos** [comment]
> Hell no. Monofoxe is game-agnostic and will stay that way. Any specific inputs should be defined by your game.

I agree, but there is the rub, your framework forces button actions whether or not the game wants them. Your input design is not game agnostic and slow.
