### ISSUE TITLE
Monofoxe.Playground

### ISSUE THREAD

**Issue by Monenvoy** [gnFur/Monofoxe#3]
Had to create "C:\Program Files (x86)\Monofoxe Engine\v2-dev\NoPipeline". Still doesn't work though.

![zaebalo](https://user-images.githubusercontent.com/48245086/73877269-33db3480-480d-11ea-8118-c44f06d9fffb.PNG)

**Comment by Martenfur** [comment]
Try installing the latest Monofoxe dev build. Also check if the Pipefoxe project is present in the solution. I believe I've added/wanted to add it there at some point but may have forgotten or haven't merged it yet. If it's not there, open monofoxe solution and build Pipefoxe. 
I'll add a Pipefoxe check tomorrow in the samples.

**Comment by Monenvoy** [comment]
I added dependence on Pipefoxe everywhere, so it works now. Don't need to do it in the latest build
