### ISSUE TITLE
Pipefoxe can't parse Tiled text properties

### ISSUE THREAD

**Issue by PeriBooty** [gnFur/Monofoxe#5]
Pipefoxe fails to parse custom text properties in Tiled maps. For example, the following object in a Tiled map fails to parse:
```xml
<object id="7" name="Sign" type="Interaction" x="260" y="80" width="40" height="20">
  <properties>
    <property name="InteractionText">* This is a sign.
* That's about it.</property>
  </properties>
</object>
```
I've tracked down the possible culprit in [XmlHelper.cs:25](https://github.com/Martenfur/Monofoxe/blob/10048b1eb0524a3cdc9bfbd54e6499c940ecaeae/Monofoxe/Pipefoxe/Tiled/XmlHelper.cs#L25).

While other's custom properties use this `value` attribute, the custom text property does not, instead placing the value inside of itself, as seen in the example. This causes Pipefoxe to throw an exception while parsing.

**Comment by Martenfur** [comment]
I hate Tiled format so fucking much. : D
It's exceptions upon exception upon exceptions.
Either way, fixed the thing.
