### ISSUE TITLE
No Mac OS build

### ISSUE THREAD

**Issue by bbunks** [gnFur/Monofoxe#6]
I would be interested in a build for mac OS becauseI use Mac as my primary development OS. Would this be something you are considering in the future?

**Comment by Martenfur** [comment]
Nope. I do not support Apple platforms. I can only advice to install Bootcamp or use Monofoxe libraries manually, since technically they'll be able to work on any OS.

**Comment by Martenfur** [comment]
Version 2.0 actually supports macos now, lole.

**Comment by bbunks** [comment]
I will have to give it a look.
